[build]
  # Build command for Next.js
  command = "yarn build"
  
  # Publish directory (Next.js static export output)
  publish = "out"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Yarn version
  YARN_VERSION = "1.22.22"

# Redirect rules for Next.js App Router
[[redirects]]
  # Handle client-side routing for Next.js App Router
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache Next.js build files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle Next.js API routes (if any)
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Handle Next.js image optimization
[[redirects]]
  from = "/_next/image*"
  to = "/_next/image/:splat"
  status = 200

# Environment variables (add your specific ones here)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
