[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true

# Verification settings
[profile.default.etherscan]
liskSepolia = { key = "${ETHERSCAN_API_KEY}" }
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
